# Generated by Django 4.0.5 on 2022-07-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_rename_product_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
    ]
